# Generated by Django 3.0.2 on 2020-03-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvetchupapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='email',
            field=models.EmailField(default='fakeemail@site.com', max_length=254),
            preserve_default=False,
        ),
    ]
