# Generated by Django 3.0.2 on 2020-03-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvetchupapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['review_date']},
        ),
    ]
