# Generated by Django 3.0.2 on 2020-03-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvetchupapp', '0002_site_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='phone_number',
            field=models.CharField(default='xxx-xxx-xxxx', max_length=200),
        ),
    ]
