# Generated by Django 3.0.2 on 2020-03-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvetchupapp', '0003_site_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
