# Generated by Django 3.0.2 on 2020-04-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvetchupapp', '0004_site_fake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='fake',
        ),
    ]
