# Generated by Django 3.0.2 on 2020-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvetchupapp', '0004_auto_20200316_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='customer_support_page',
            field=models.URLField(default=''),
        ),
    ]
