# Generated by Django 3.0.2 on 2020-03-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvetchupapp', '0005_site_customer_support_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='customer_support_page',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
